//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlertFrequency.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AlertFrequency">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DoNotAlert"/>
 *     &lt;enumeration value="AlertOnce"/>
 *     &lt;enumeration value="AlertDaily"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AlertFrequency")
@XmlEnum
public enum AlertFrequency {

    @XmlEnumValue("DoNotAlert")
    DO_NOT_ALERT("DoNotAlert"),
    @XmlEnumValue("AlertOnce")
    ALERT_ONCE("AlertOnce"),
    @XmlEnumValue("AlertDaily")
    ALERT_DAILY("AlertDaily");
    private final String value;

    AlertFrequency(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlertFrequency fromValue(String v) {
        for (AlertFrequency c: AlertFrequency.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
