//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssignedDevicesType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="AssignedDevicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VirtualMachines" type="{}VirtualMachineReferencesType" minOccurs="0"/>
 *         &lt;element name="PhysicalDevices" type="{}PhysicalDeviceReferencesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssignedDevicesType", propOrder = {
    "virtualMachines",
    "physicalDevices"
})
public class AssignedDevicesType {

    @XmlElementRef(name = "VirtualMachines", type = JAXBElement.class, required = false)
    protected JAXBElement<VirtualMachineReferencesType> virtualMachines;
    @XmlElementRef(name = "PhysicalDevices", type = JAXBElement.class, required = false)
    protected JAXBElement<PhysicalDeviceReferencesType> physicalDevices;

    /**
     * Gets the value of the virtualMachines property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link VirtualMachineReferencesType }{@code >}
     */
    public JAXBElement<VirtualMachineReferencesType> getVirtualMachines() {
        return virtualMachines;
    }

    /**
     * Sets the value of the virtualMachines property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link VirtualMachineReferencesType }{@code >}
     */
    public void setVirtualMachines(JAXBElement<VirtualMachineReferencesType> value) {
        this.virtualMachines = value;
    }

    /**
     * Gets the value of the physicalDevices property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link PhysicalDeviceReferencesType }{@code >}
     */
    public JAXBElement<PhysicalDeviceReferencesType> getPhysicalDevices() {
        return physicalDevices;
    }

    /**
     * Sets the value of the physicalDevices property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link PhysicalDeviceReferencesType }{@code >}
     */
    public void setPhysicalDevices(JAXBElement<PhysicalDeviceReferencesType> value) {
        this.physicalDevices = value;
    }

}
