//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for BillingCostType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="BillingCostType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Total" type="{}CostType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillingCostType", propOrder = {
    "total"
})
@XmlSeeAlso({
    DeviceStorageCostType.class,
    ReservedBillingType.class,
    DeviceCloudServiceUsageType.class,
    InstanceBasedBillingType.class,
    BurstingCostType.class,
    ComputeCostType.class,
    StorageCostType.class,
    DeviceLicensedSoftwareCostType.class,
    DeviceComputeCostType.class,
    CloudServiceBillingItemType.class,
    DeviceCloudServicePackageUsageType.class,
    DeviceCloudServiceCostType.class,
    CloudServiceCostType.class,
    LicenseCostType.class,
    CloudServicePackageBillingItemType.class
})
public class BillingCostType {

    @XmlElementRef(name = "Total", type = JAXBElement.class, required = false)
    protected JAXBElement<CostType> total;

    /**
     * Gets the value of the total property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link CostType }{@code >}
     */
    public JAXBElement<CostType> getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link CostType }{@code >}
     */
    public void setTotal(JAXBElement<CostType> value) {
        this.total = value;
    }

}
