//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for BusinessOperationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="BusinessOperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="BusinessOperationType" type="{}BusinessOperationTypeEnum" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsAssignable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsSecurityGroupOperation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessOperationType", propOrder = {
    "businessOperationType",
    "description",
    "isAssignable",
    "isSecurityGroupOperation"
})
public class BusinessOperationType
    extends ResourceType {

    @XmlElement(name = "BusinessOperationType")
    @XmlSchemaType(name = "string")
    protected BusinessOperationTypeEnum businessOperationType;
    @XmlElementRef(name = "Description", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;
    @XmlElement(name = "IsAssignable")
    protected Boolean isAssignable;
    @XmlElement(name = "IsSecurityGroupOperation")
    protected Boolean isSecurityGroupOperation;

    /**
     * Gets the value of the businessOperationType property.
     *
     * @return possible object is
     * {@link BusinessOperationTypeEnum }
     */
    public BusinessOperationTypeEnum getBusinessOperationType() {
        return businessOperationType;
    }

    /**
     * Sets the value of the businessOperationType property.
     *
     * @param value allowed object is
     *              {@link BusinessOperationTypeEnum }
     */
    public void setBusinessOperationType(BusinessOperationTypeEnum value) {
        this.businessOperationType = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the isAssignable property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsAssignable() {
        return isAssignable;
    }

    /**
     * Sets the value of the isAssignable property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsAssignable(Boolean value) {
        this.isAssignable = value;
    }

    /**
     * Gets the value of the isSecurityGroupOperation property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsSecurityGroupOperation() {
        return isSecurityGroupOperation;
    }

    /**
     * Sets the value of the isSecurityGroupOperation property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsSecurityGroupOperation(Boolean value) {
        this.isSecurityGroupOperation = value;
    }

}
