//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.math.BigDecimal;


/**
 * <p>Java class for CatalogEntryConfigurationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CatalogEntryConfigurationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="ProcessorCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Memory" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="OperatingSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Disks" type="{}DisksType" minOccurs="0"/>
 *         &lt;element name="NetworkAdapters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NetworkMappings" type="{}CatalogNetworkMappingsType" minOccurs="0"/>
 *         &lt;element name="LicensedBy" type="{}CatalogItemLicensedBy" minOccurs="0"/>
 *         &lt;element name="LicenseType" type="{}CatalogItemLicenseTypeEnum" minOccurs="0"/>
 *         &lt;element name="LicenseCost" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogEntryConfigurationType", propOrder = {
    "processorCount",
    "memory",
    "operatingSystem",
    "disks",
    "networkAdapters",
    "networkMappings",
    "licensedBy",
    "licenseType",
    "licenseCost"
})
public class CatalogEntryConfigurationType
    extends ResourceType {

    @XmlElement(name = "ProcessorCount")
    protected Integer processorCount;
    @XmlElementRef(name = "Memory", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> memory;
    @XmlElementRef(name = "OperatingSystem", type = JAXBElement.class, required = false)
    protected JAXBElement<String> operatingSystem;
    @XmlElementRef(name = "Disks", type = JAXBElement.class, required = false)
    protected JAXBElement<DisksType> disks;
    @XmlElement(name = "NetworkAdapters")
    protected Integer networkAdapters;
    @XmlElementRef(name = "NetworkMappings", type = JAXBElement.class, required = false)
    protected JAXBElement<CatalogNetworkMappingsType> networkMappings;
    @XmlElement(name = "LicensedBy")
    @XmlSchemaType(name = "string")
    protected CatalogItemLicensedBy licensedBy;
    @XmlElement(name = "LicenseType")
    @XmlSchemaType(name = "string")
    protected CatalogItemLicenseTypeEnum licenseType;
    @XmlElement(name = "LicenseCost")
    protected BigDecimal licenseCost;

    /**
     * Gets the value of the processorCount property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getProcessorCount() {
        return processorCount;
    }

    /**
     * Sets the value of the processorCount property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setProcessorCount(Integer value) {
        this.processorCount = value;
    }

    /**
     * Gets the value of the memory property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setMemory(JAXBElement<ResourceUnitType> value) {
        this.memory = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setOperatingSystem(JAXBElement<String> value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the disks property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link DisksType }{@code >}
     */
    public JAXBElement<DisksType> getDisks() {
        return disks;
    }

    /**
     * Sets the value of the disks property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link DisksType }{@code >}
     */
    public void setDisks(JAXBElement<DisksType> value) {
        this.disks = value;
    }

    /**
     * Gets the value of the networkAdapters property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getNetworkAdapters() {
        return networkAdapters;
    }

    /**
     * Sets the value of the networkAdapters property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setNetworkAdapters(Integer value) {
        this.networkAdapters = value;
    }

    /**
     * Gets the value of the networkMappings property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link CatalogNetworkMappingsType }{@code >}
     */
    public JAXBElement<CatalogNetworkMappingsType> getNetworkMappings() {
        return networkMappings;
    }

    /**
     * Sets the value of the networkMappings property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link CatalogNetworkMappingsType }{@code >}
     */
    public void setNetworkMappings(JAXBElement<CatalogNetworkMappingsType> value) {
        this.networkMappings = value;
    }

    /**
     * Gets the value of the licensedBy property.
     *
     * @return possible object is
     * {@link CatalogItemLicensedBy }
     */
    public CatalogItemLicensedBy getLicensedBy() {
        return licensedBy;
    }

    /**
     * Sets the value of the licensedBy property.
     *
     * @param value allowed object is
     *              {@link CatalogItemLicensedBy }
     */
    public void setLicensedBy(CatalogItemLicensedBy value) {
        this.licensedBy = value;
    }

    /**
     * Gets the value of the licenseType property.
     *
     * @return possible object is
     * {@link CatalogItemLicenseTypeEnum }
     */
    public CatalogItemLicenseTypeEnum getLicenseType() {
        return licenseType;
    }

    /**
     * Sets the value of the licenseType property.
     *
     * @param value allowed object is
     *              {@link CatalogItemLicenseTypeEnum }
     */
    public void setLicenseType(CatalogItemLicenseTypeEnum value) {
        this.licenseType = value;
    }

    /**
     * Gets the value of the licenseCost property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getLicenseCost() {
        return licenseCost;
    }

    /**
     * Sets the value of the licenseCost property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setLicenseCost(BigDecimal value) {
        this.licenseCost = value;
    }

}
