//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CatalogItemFileType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CatalogItemFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UploadUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Size" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="BytesTransferred" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Status" type="{}FileUploadStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogItemFileType", propOrder = {
    "uploadUrl",
    "name",
    "size",
    "bytesTransferred",
    "status"
})
public class CatalogItemFileType {

    @XmlElementRef(name = "UploadUrl", type = JAXBElement.class, required = false)
    protected JAXBElement<String> uploadUrl;
    @XmlElementRef(name = "Name", type = JAXBElement.class, required = false)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "Size", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> size;
    @XmlElement(name = "BytesTransferred")
    protected Long bytesTransferred;
    @XmlElement(name = "Status")
    @XmlSchemaType(name = "string")
    protected FileUploadStatus status;

    /**
     * Gets the value of the uploadUrl property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getUploadUrl() {
        return uploadUrl;
    }

    /**
     * Sets the value of the uploadUrl property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setUploadUrl(JAXBElement<String> value) {
        this.uploadUrl = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setName(JAXBElement<String> value) {
        this.name = value;
    }

    /**
     * Gets the value of the size property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setSize(JAXBElement<ResourceUnitType> value) {
        this.size = value;
    }

    /**
     * Gets the value of the bytesTransferred property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBytesTransferred() {
        return bytesTransferred;
    }

    /**
     * Sets the value of the bytesTransferred property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBytesTransferred(Long value) {
        this.bytesTransferred = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link FileUploadStatus }
     */
    public FileUploadStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link FileUploadStatus }
     */
    public void setStatus(FileUploadStatus value) {
        this.status = value;
    }

}
