//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CatalogLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogLocationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="Storage" type="{}CatalogStorageType" minOccurs="0"/>
 *         &lt;element name="Catalog" type="{}CatalogEntriesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogLocationType", propOrder = {
    "storage",
    "catalog"
})
public class CatalogLocationType
    extends EntityType
{

    @XmlElementRef(name = "Storage", type = JAXBElement.class, required = false)
    protected JAXBElement<CatalogStorageType> storage;
    @XmlElementRef(name = "Catalog", type = JAXBElement.class, required = false)
    protected JAXBElement<CatalogEntriesType> catalog;

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CatalogStorageType }{@code >}
     *     
     */
    public JAXBElement<CatalogStorageType> getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CatalogStorageType }{@code >}
     *     
     */
    public void setStorage(JAXBElement<CatalogStorageType> value) {
        this.storage = value;
    }

    /**
     * Gets the value of the catalog property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CatalogEntriesType }{@code >}
     *     
     */
    public JAXBElement<CatalogEntriesType> getCatalog() {
        return catalog;
    }

    /**
     * Sets the value of the catalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CatalogEntriesType }{@code >}
     *     
     */
    public void setCatalog(JAXBElement<CatalogEntriesType> value) {
        this.catalog = value;
    }

}
