//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ComputeResourceSummaryType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ComputeResourceSummaryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Allocated" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Consumed" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Purchased" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Utilization" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputeResourceSummaryType", propOrder = {
    "allocated",
    "consumed",
    "purchased",
    "utilization"
})
@XmlSeeAlso({
    MemoryComputeResourceSummaryType.class,
    CpuComputeResourceSummaryType.class
})
public class ComputeResourceSummaryType {

    @XmlElementRef(name = "Allocated", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> allocated;
    @XmlElementRef(name = "Consumed", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> consumed;
    @XmlElementRef(name = "Purchased", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> purchased;
    @XmlElementRef(name = "Utilization", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> utilization;

    /**
     * Gets the value of the allocated property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getAllocated() {
        return allocated;
    }

    /**
     * Sets the value of the allocated property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setAllocated(JAXBElement<ResourceUnitType> value) {
        this.allocated = value;
    }

    /**
     * Gets the value of the consumed property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getConsumed() {
        return consumed;
    }

    /**
     * Sets the value of the consumed property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setConsumed(JAXBElement<ResourceUnitType> value) {
        this.consumed = value;
    }

    /**
     * Gets the value of the purchased property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getPurchased() {
        return purchased;
    }

    /**
     * Sets the value of the purchased property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setPurchased(JAXBElement<ResourceUnitType> value) {
        this.purchased = value;
    }

    /**
     * Gets the value of the utilization property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public JAXBElement<Integer> getUtilization() {
        return utilization;
    }

    /**
     * Sets the value of the utilization property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public void setUtilization(JAXBElement<Integer> value) {
        this.utilization = value;
    }

}
