//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComputeCostType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComputeCostType">
 *   &lt;complexContent>
 *     &lt;extension base="{}BillingCostType">
 *       &lt;sequence>
 *         &lt;element name="VirtualMachines" type="{}VirtualMachineUsageReferencesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputeCostType", propOrder = {
    "virtualMachines"
})
public class ComputeCostType
    extends BillingCostType
{

    @XmlElementRef(name = "VirtualMachines", type = JAXBElement.class, required = false)
    protected JAXBElement<VirtualMachineUsageReferencesType> virtualMachines;

    /**
     * Gets the value of the virtualMachines property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link VirtualMachineUsageReferencesType }{@code >}
     *     
     */
    public JAXBElement<VirtualMachineUsageReferencesType> getVirtualMachines() {
        return virtualMachines;
    }

    /**
     * Sets the value of the virtualMachines property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link VirtualMachineUsageReferencesType }{@code >}
     *     
     */
    public void setVirtualMachines(JAXBElement<VirtualMachineUsageReferencesType> value) {
        this.virtualMachines = value;
    }

}
