//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComputePoolType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ComputePoolType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="VirtualMachines" type="{}VirtualMachineReferencesType" minOccurs="0"/>
 *         &lt;element name="Purchased" type="{}ComputePoolCapacityType" minOccurs="0"/>
 *         &lt;element name="CpuBurst" type="{}ResourceBurstType" minOccurs="0"/>
 *         &lt;element name="MemoryBurst" type="{}ResourceBurstType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputePoolType", propOrder = {
    "virtualMachines",
    "purchased",
    "cpuBurst",
    "memoryBurst"
})
public class ComputePoolType
    extends EntityType {

    @XmlElementRef(name = "VirtualMachines", type = JAXBElement.class, required = false)
    protected JAXBElement<VirtualMachineReferencesType> virtualMachines;
    @XmlElementRef(name = "Purchased", type = JAXBElement.class, required = false)
    protected JAXBElement<ComputePoolCapacityType> purchased;
    @XmlElementRef(name = "CpuBurst", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceBurstType> cpuBurst;
    @XmlElementRef(name = "MemoryBurst", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceBurstType> memoryBurst;

    /**
     * Gets the value of the virtualMachines property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link VirtualMachineReferencesType }{@code >}
     */
    public JAXBElement<VirtualMachineReferencesType> getVirtualMachines() {
        return virtualMachines;
    }

    /**
     * Sets the value of the virtualMachines property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link VirtualMachineReferencesType }{@code >}
     */
    public void setVirtualMachines(JAXBElement<VirtualMachineReferencesType> value) {
        this.virtualMachines = value;
    }

    /**
     * Gets the value of the purchased property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ComputePoolCapacityType }{@code >}
     */
    public JAXBElement<ComputePoolCapacityType> getPurchased() {
        return purchased;
    }

    /**
     * Sets the value of the purchased property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ComputePoolCapacityType }{@code >}
     */
    public void setPurchased(JAXBElement<ComputePoolCapacityType> value) {
        this.purchased = value;
    }

    /**
     * Gets the value of the cpuBurst property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceBurstType }{@code >}
     */
    public JAXBElement<ResourceBurstType> getCpuBurst() {
        return cpuBurst;
    }

    /**
     * Sets the value of the cpuBurst property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceBurstType }{@code >}
     */
    public void setCpuBurst(JAXBElement<ResourceBurstType> value) {
        this.cpuBurst = value;
    }

    /**
     * Gets the value of the memoryBurst property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceBurstType }{@code >}
     */
    public JAXBElement<ResourceBurstType> getMemoryBurst() {
        return memoryBurst;
    }

    /**
     * Sets the value of the memoryBurst property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceBurstType }{@code >}
     */
    public void setMemoryBurst(JAXBElement<ResourceBurstType> value) {
        this.memoryBurst = value;
    }

}
