//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ComputePoolCpuUsageType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ComputePoolCpuUsageType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="CpuUsageDetailSummary" type="{}CpuUsageDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComputePoolCpuUsageType", propOrder = {
    "startTime",
    "endTime",
    "cpuUsageDetailSummary"
})
public class ComputePoolCpuUsageType
    extends ResourceType {

    @XmlElement(name = "StartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "EndTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlElementRef(name = "CpuUsageDetailSummary", type = JAXBElement.class, required = false)
    protected JAXBElement<CpuUsageDetailsType> cpuUsageDetailSummary;

    /**
     * Gets the value of the startTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the cpuUsageDetailSummary property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link CpuUsageDetailsType }{@code >}
     */
    public JAXBElement<CpuUsageDetailsType> getCpuUsageDetailSummary() {
        return cpuUsageDetailSummary;
    }

    /**
     * Sets the value of the cpuUsageDetailSummary property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link CpuUsageDetailsType }{@code >}
     */
    public void setCpuUsageDetailSummary(JAXBElement<CpuUsageDetailsType> value) {
        this.cpuUsageDetailSummary = value;
    }

}
