//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigurationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ConfigurationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmailConfiguration" type="{}NotifyByEmailConfigurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConfigurationType", propOrder = {
    "emailConfiguration"
})
public class ConfigurationType {

    @XmlElementRef(name = "EmailConfiguration", type = JAXBElement.class, required = false)
    protected JAXBElement<NotifyByEmailConfigurationType> emailConfiguration;

    /**
     * Gets the value of the emailConfiguration property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link NotifyByEmailConfigurationType }{@code >}
     */
    public JAXBElement<NotifyByEmailConfigurationType> getEmailConfiguration() {
        return emailConfiguration;
    }

    /**
     * Sets the value of the emailConfiguration property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link NotifyByEmailConfigurationType }{@code >}
     */
    public void setEmailConfiguration(JAXBElement<NotifyByEmailConfigurationType> value) {
        this.emailConfiguration = value;
    }

}
