//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CopyVirtualMachineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CopyVirtualMachineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Source" type="{}ReferenceType"/>
 *         &lt;element name="DestinationComputePool" type="{}ReferenceType" minOccurs="0"/>
 *         &lt;element name="ProcessorCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Memory" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Layout" type="{}LayoutRequestType" minOccurs="0"/>
 *         &lt;element name="DisableCustomization" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="LinuxCustomization" type="{}LinuxCustomizationType" minOccurs="0"/>
 *         &lt;element name="WindowsCustomization" type="{}WindowsCustomizationType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tags" type="{}TagsType" minOccurs="0"/>
 *         &lt;element name="PoweredOn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CopyVirtualMachineType", propOrder = {
    "source",
    "destinationComputePool",
    "processorCount",
    "memory",
    "layout",
    "disableCustomization",
    "linuxCustomization",
    "windowsCustomization",
    "description",
    "tags",
    "poweredOn"
})
public class CopyVirtualMachineType {

    @XmlElement(name = "Source", required = true, nillable = true)
    protected ReferenceType source;
    @XmlElementRef(name = "DestinationComputePool", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> destinationComputePool;
    @XmlElement(name = "ProcessorCount")
    protected Integer processorCount;
    @XmlElementRef(name = "Memory", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> memory;
    @XmlElementRef(name = "Layout", type = JAXBElement.class, required = false)
    protected JAXBElement<LayoutRequestType> layout;
    @XmlElementRef(name = "DisableCustomization", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> disableCustomization;
    @XmlElementRef(name = "LinuxCustomization", type = JAXBElement.class, required = false)
    protected JAXBElement<LinuxCustomizationType> linuxCustomization;
    @XmlElementRef(name = "WindowsCustomization", type = JAXBElement.class, required = false)
    protected JAXBElement<WindowsCustomizationType> windowsCustomization;
    @XmlElementRef(name = "Description", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;
    @XmlElementRef(name = "Tags", type = JAXBElement.class, required = false)
    protected JAXBElement<TagsType> tags;
    @XmlElementRef(name = "PoweredOn", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> poweredOn;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setSource(ReferenceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the destinationComputePool property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     
     */
    public JAXBElement<ReferenceType> getDestinationComputePool() {
        return destinationComputePool;
    }

    /**
     * Sets the value of the destinationComputePool property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     
     */
    public void setDestinationComputePool(JAXBElement<ReferenceType> value) {
        this.destinationComputePool = value;
    }

    /**
     * Gets the value of the processorCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProcessorCount() {
        return processorCount;
    }

    /**
     * Sets the value of the processorCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProcessorCount(Integer value) {
        this.processorCount = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     *     
     */
    public JAXBElement<ResourceUnitType> getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     *     
     */
    public void setMemory(JAXBElement<ResourceUnitType> value) {
        this.memory = value;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LayoutRequestType }{@code >}
     *     
     */
    public JAXBElement<LayoutRequestType> getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LayoutRequestType }{@code >}
     *     
     */
    public void setLayout(JAXBElement<LayoutRequestType> value) {
        this.layout = value;
    }

    /**
     * Gets the value of the disableCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getDisableCustomization() {
        return disableCustomization;
    }

    /**
     * Sets the value of the disableCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setDisableCustomization(JAXBElement<Boolean> value) {
        this.disableCustomization = value;
    }

    /**
     * Gets the value of the linuxCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LinuxCustomizationType }{@code >}
     *     
     */
    public JAXBElement<LinuxCustomizationType> getLinuxCustomization() {
        return linuxCustomization;
    }

    /**
     * Sets the value of the linuxCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LinuxCustomizationType }{@code >}
     *     
     */
    public void setLinuxCustomization(JAXBElement<LinuxCustomizationType> value) {
        this.linuxCustomization = value;
    }

    /**
     * Gets the value of the windowsCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WindowsCustomizationType }{@code >}
     *     
     */
    public JAXBElement<WindowsCustomizationType> getWindowsCustomization() {
        return windowsCustomization;
    }

    /**
     * Sets the value of the windowsCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WindowsCustomizationType }{@code >}
     *     
     */
    public void setWindowsCustomization(JAXBElement<WindowsCustomizationType> value) {
        this.windowsCustomization = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link TagsType }{@code >}
     *     
     */
    public JAXBElement<TagsType> getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link TagsType }{@code >}
     *     
     */
    public void setTags(JAXBElement<TagsType> value) {
        this.tags = value;
    }

    /**
     * Gets the value of the poweredOn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getPoweredOn() {
        return poweredOn;
    }

    /**
     * Sets the value of the poweredOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setPoweredOn(JAXBElement<Boolean> value) {
        this.poweredOn = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
