//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CreateVirtualMachineRequestType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CreateVirtualMachineRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProcessorCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Memory" type="{}ResourceUnitType"/>
 *         &lt;element name="Layout" type="{}LayoutRequestType"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tags" type="{}TagsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateVirtualMachineRequestType", propOrder = {
    "processorCount",
    "memory",
    "layout",
    "description",
    "tags"
})
@XmlSeeAlso({
    CreateBlankVirtualMachineType.class,
    CreateOsTemplateVirtualMachineRequestType.class,
    ImportVirtualMachineType.class
})
public class CreateVirtualMachineRequestType {

    @XmlElement(name = "ProcessorCount")
    protected int processorCount;
    @XmlElement(name = "Memory", required = true, nillable = true)
    protected ResourceUnitType memory;
    @XmlElement(name = "Layout", required = true, nillable = true)
    protected LayoutRequestType layout;
    @XmlElementRef(name = "Description", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;
    @XmlElementRef(name = "Tags", type = JAXBElement.class, required = false)
    protected JAXBElement<TagsType> tags;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the processorCount property.
     */
    public int getProcessorCount() {
        return processorCount;
    }

    /**
     * Sets the value of the processorCount property.
     */
    public void setProcessorCount(int value) {
        this.processorCount = value;
    }

    /**
     * Gets the value of the memory property.
     *
     * @return possible object is
     * {@link ResourceUnitType }
     */
    public ResourceUnitType getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     *
     * @param value allowed object is
     *              {@link ResourceUnitType }
     */
    public void setMemory(ResourceUnitType value) {
        this.memory = value;
    }

    /**
     * Gets the value of the layout property.
     *
     * @return possible object is
     * {@link LayoutRequestType }
     */
    public LayoutRequestType getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     *
     * @param value allowed object is
     *              {@link LayoutRequestType }
     */
    public void setLayout(LayoutRequestType value) {
        this.layout = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the tags property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link TagsType }{@code >}
     */
    public JAXBElement<TagsType> getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link TagsType }{@code >}
     */
    public void setTags(JAXBElement<TagsType> value) {
        this.tags = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

}
