//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for CreateOsTemplateVirtualMachineRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreateOsTemplateVirtualMachineRequestType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CreateVirtualMachineRequestType">
 *       &lt;sequence>
 *         &lt;element name="LinuxCustomization" type="{}LinuxCustomizationType" minOccurs="0"/>
 *         &lt;element name="WindowsCustomization" type="{}WindowsCustomizationType" minOccurs="0"/>
 *         &lt;element name="PoweredOn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateOsTemplateVirtualMachineRequestType", propOrder = {
    "linuxCustomization",
    "windowsCustomization",
    "poweredOn"
})
@XmlSeeAlso({
    CreateVirtualMachineType.class
})
public class CreateOsTemplateVirtualMachineRequestType
    extends CreateVirtualMachineRequestType
{

    @XmlElementRef(name = "LinuxCustomization", type = JAXBElement.class, required = false)
    protected JAXBElement<LinuxCustomizationType> linuxCustomization;
    @XmlElementRef(name = "WindowsCustomization", type = JAXBElement.class, required = false)
    protected JAXBElement<WindowsCustomizationType> windowsCustomization;
    @XmlElementRef(name = "PoweredOn", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> poweredOn;

    /**
     * Gets the value of the linuxCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LinuxCustomizationType }{@code >}
     *     
     */
    public JAXBElement<LinuxCustomizationType> getLinuxCustomization() {
        return linuxCustomization;
    }

    /**
     * Sets the value of the linuxCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LinuxCustomizationType }{@code >}
     *     
     */
    public void setLinuxCustomization(JAXBElement<LinuxCustomizationType> value) {
        this.linuxCustomization = value;
    }

    /**
     * Gets the value of the windowsCustomization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WindowsCustomizationType }{@code >}
     *     
     */
    public JAXBElement<WindowsCustomizationType> getWindowsCustomization() {
        return windowsCustomization;
    }

    /**
     * Sets the value of the windowsCustomization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WindowsCustomizationType }{@code >}
     *     
     */
    public void setWindowsCustomization(JAXBElement<WindowsCustomizationType> value) {
        this.windowsCustomization = value;
    }

    /**
     * Gets the value of the poweredOn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getPoweredOn() {
        return poweredOn;
    }

    /**
     * Sets the value of the poweredOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setPoweredOn(JAXBElement<Boolean> value) {
        this.poweredOn = value;
    }

}
