//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CurrentSnapshotStatusType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="CurrentSnapshotStatusType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="MostRecentSnapshotTask" type="{}TaskType" minOccurs="0"/>
 *         &lt;element name="NextRunTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SnapshotOverheadStorage" type="{}ResourceUnitType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurrentSnapshotStatusType", propOrder = {
    "mostRecentSnapshotTask",
    "nextRunTime",
    "snapshotOverheadStorage"
})
public class CurrentSnapshotStatusType
    extends ResourceType {

    @XmlElementRef(name = "MostRecentSnapshotTask", type = JAXBElement.class, required = false)
    protected JAXBElement<TaskType> mostRecentSnapshotTask;
    @XmlElementRef(name = "NextRunTime", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> nextRunTime;
    @XmlElementRef(name = "SnapshotOverheadStorage", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> snapshotOverheadStorage;

    /**
     * Gets the value of the mostRecentSnapshotTask property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link TaskType }{@code >}
     */
    public JAXBElement<TaskType> getMostRecentSnapshotTask() {
        return mostRecentSnapshotTask;
    }

    /**
     * Sets the value of the mostRecentSnapshotTask property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link TaskType }{@code >}
     */
    public void setMostRecentSnapshotTask(JAXBElement<TaskType> value) {
        this.mostRecentSnapshotTask = value;
    }

    /**
     * Gets the value of the nextRunTime property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getNextRunTime() {
        return nextRunTime;
    }

    /**
     * Sets the value of the nextRunTime property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public void setNextRunTime(JAXBElement<XMLGregorianCalendar> value) {
        this.nextRunTime = value;
    }

    /**
     * Gets the value of the snapshotOverheadStorage property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getSnapshotOverheadStorage() {
        return snapshotOverheadStorage;
    }

    /**
     * Sets the value of the snapshotOverheadStorage property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setSnapshotOverheadStorage(JAXBElement<ResourceUnitType> value) {
        this.snapshotOverheadStorage = value;
    }

}
