//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomPasswordRulesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomPasswordRulesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinimumCharacters" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumUpperCaseCharacters" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumLowerCaseCharacters" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumNumericCharacters" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumSpecialCharacters" type="{}EnabledValueType"/>
 *         &lt;element name="MaximumConsecutiveCharactersFromPriorPassword" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumLifetimeRestriction" type="{}EnabledValueType"/>
 *         &lt;element name="MinimumGenerationsBeforeReuse" type="{}EnabledValueType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomPasswordRulesType", propOrder = {
    "minimumCharacters",
    "minimumUpperCaseCharacters",
    "minimumLowerCaseCharacters",
    "minimumNumericCharacters",
    "minimumSpecialCharacters",
    "maximumConsecutiveCharactersFromPriorPassword",
    "minimumLifetimeRestriction",
    "minimumGenerationsBeforeReuse"
})
public class CustomPasswordRulesType {

    @XmlElement(name = "MinimumCharacters", required = true, nillable = true)
    protected EnabledValueType minimumCharacters;
    @XmlElement(name = "MinimumUpperCaseCharacters", required = true, nillable = true)
    protected EnabledValueType minimumUpperCaseCharacters;
    @XmlElement(name = "MinimumLowerCaseCharacters", required = true, nillable = true)
    protected EnabledValueType minimumLowerCaseCharacters;
    @XmlElement(name = "MinimumNumericCharacters", required = true, nillable = true)
    protected EnabledValueType minimumNumericCharacters;
    @XmlElement(name = "MinimumSpecialCharacters", required = true, nillable = true)
    protected EnabledValueType minimumSpecialCharacters;
    @XmlElement(name = "MaximumConsecutiveCharactersFromPriorPassword", required = true, nillable = true)
    protected EnabledValueType maximumConsecutiveCharactersFromPriorPassword;
    @XmlElement(name = "MinimumLifetimeRestriction", required = true, nillable = true)
    protected EnabledValueType minimumLifetimeRestriction;
    @XmlElement(name = "MinimumGenerationsBeforeReuse", required = true, nillable = true)
    protected EnabledValueType minimumGenerationsBeforeReuse;

    /**
     * Gets the value of the minimumCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumCharacters() {
        return minimumCharacters;
    }

    /**
     * Sets the value of the minimumCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumCharacters(EnabledValueType value) {
        this.minimumCharacters = value;
    }

    /**
     * Gets the value of the minimumUpperCaseCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumUpperCaseCharacters() {
        return minimumUpperCaseCharacters;
    }

    /**
     * Sets the value of the minimumUpperCaseCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumUpperCaseCharacters(EnabledValueType value) {
        this.minimumUpperCaseCharacters = value;
    }

    /**
     * Gets the value of the minimumLowerCaseCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumLowerCaseCharacters() {
        return minimumLowerCaseCharacters;
    }

    /**
     * Sets the value of the minimumLowerCaseCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumLowerCaseCharacters(EnabledValueType value) {
        this.minimumLowerCaseCharacters = value;
    }

    /**
     * Gets the value of the minimumNumericCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumNumericCharacters() {
        return minimumNumericCharacters;
    }

    /**
     * Sets the value of the minimumNumericCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumNumericCharacters(EnabledValueType value) {
        this.minimumNumericCharacters = value;
    }

    /**
     * Gets the value of the minimumSpecialCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumSpecialCharacters() {
        return minimumSpecialCharacters;
    }

    /**
     * Sets the value of the minimumSpecialCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumSpecialCharacters(EnabledValueType value) {
        this.minimumSpecialCharacters = value;
    }

    /**
     * Gets the value of the maximumConsecutiveCharactersFromPriorPassword property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMaximumConsecutiveCharactersFromPriorPassword() {
        return maximumConsecutiveCharactersFromPriorPassword;
    }

    /**
     * Sets the value of the maximumConsecutiveCharactersFromPriorPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMaximumConsecutiveCharactersFromPriorPassword(EnabledValueType value) {
        this.maximumConsecutiveCharactersFromPriorPassword = value;
    }

    /**
     * Gets the value of the minimumLifetimeRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumLifetimeRestriction() {
        return minimumLifetimeRestriction;
    }

    /**
     * Sets the value of the minimumLifetimeRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumLifetimeRestriction(EnabledValueType value) {
        this.minimumLifetimeRestriction = value;
    }

    /**
     * Gets the value of the minimumGenerationsBeforeReuse property.
     * 
     * @return
     *     possible object is
     *     {@link EnabledValueType }
     *     
     */
    public EnabledValueType getMinimumGenerationsBeforeReuse() {
        return minimumGenerationsBeforeReuse;
    }

    /**
     * Sets the value of the minimumGenerationsBeforeReuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnabledValueType }
     *     
     */
    public void setMinimumGenerationsBeforeReuse(EnabledValueType value) {
        this.minimumGenerationsBeforeReuse = value;
    }

}
