//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DetachDiskRetryOperationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DetachDiskRetryOperationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="DetachedDisk" type="{}ReferenceType" minOccurs="0"/>
 *         &lt;element name="VirtualMachine" type="{}ReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetachDiskRetryOperationType", propOrder = {
    "detachedDisk",
    "virtualMachine"
})
public class DetachDiskRetryOperationType
    extends ResourceType {

    @XmlElementRef(name = "DetachedDisk", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> detachedDisk;
    @XmlElementRef(name = "VirtualMachine", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> virtualMachine;

    /**
     * Gets the value of the detachedDisk property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getDetachedDisk() {
        return detachedDisk;
    }

    /**
     * Sets the value of the detachedDisk property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setDetachedDisk(JAXBElement<ReferenceType> value) {
        this.detachedDisk = value;
    }

    /**
     * Gets the value of the virtualMachine property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getVirtualMachine() {
        return virtualMachine;
    }

    /**
     * Sets the value of the virtualMachine property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setVirtualMachine(JAXBElement<ReferenceType> value) {
        this.virtualMachine = value;
    }

}
