//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for DetachedDiskReferencesResourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetachedDiskReferencesResourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="DetachedDisk" type="{}DetachedDiskReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetachedDiskReferencesResourceType", propOrder = {
    "detachedDisk"
})
@XmlSeeAlso({
    DetachedDiskReferenceListType.class
})
public class DetachedDiskReferencesResourceType
    extends ResourceType
{

    @XmlElement(name = "DetachedDisk", nillable = true)
    protected List<DetachedDiskReferenceType> detachedDisk;

    /**
     * Gets the value of the detachedDisk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detachedDisk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetachedDisk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetachedDiskReferenceType }
     * 
     * 
     */
    public List<DetachedDiskReferenceType> getDetachedDisk() {
        if (detachedDisk == null) {
            detachedDisk = new ArrayList<DetachedDiskReferenceType>();
        }
        return this.detachedDisk;
    }

}
