//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DeviceUsageReferenceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DeviceUsageReferenceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ReferenceType">
 *       &lt;sequence>
 *         &lt;element name="ComputePool" type="{}ReferenceType" minOccurs="0"/>
 *         &lt;element name="Status" type="{}DeviceStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceUsageReferenceType", propOrder = {
    "computePool",
    "status"
})
@XmlSeeAlso({
    ServerLicenseUsageReferenceType.class,
    VirtualMachineUsageReferenceType.class,
    DetachedDiskUsageReferenceType.class
})
public class DeviceUsageReferenceType
    extends ReferenceType {

    /**
     *
     */
    private static final long serialVersionUID = -4875524223421396974L;
    @XmlElementRef(name = "ComputePool", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> computePool;
    @XmlElement(name = "Status")
    @XmlSchemaType(name = "string")
    protected DeviceStatus status;

    /**
     * Gets the value of the computePool property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getComputePool() {
        return computePool;
    }

    /**
     * Sets the value of the computePool property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setComputePool(JAXBElement<ReferenceType> value) {
        this.computePool = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link DeviceStatus }
     */
    public DeviceStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link DeviceStatus }
     */
    public void setStatus(DeviceStatus value) {
        this.status = value;
    }

}
