//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceLayoutType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DeviceLayoutType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="Rows" type="{}RowsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceLayoutType", propOrder = {
    "rows"
})
public class DeviceLayoutType
    extends ResourceType {

    @XmlElementRef(name = "Rows", type = JAXBElement.class, required = false)
    protected JAXBElement<RowsType> rows;

    /**
     * Gets the value of the rows property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link RowsType }{@code >}
     */
    public JAXBElement<RowsType> getRows() {
        return rows;
    }

    /**
     * Sets the value of the rows property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link RowsType }{@code >}
     */
    public void setRows(JAXBElement<RowsType> value) {
        this.rows = value;
    }

}
