//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceMeteredBillingEnvironmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceMeteredBillingEnvironmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ReferenceType">
 *       &lt;sequence>
 *         &lt;element name="Total" type="{}CostType" minOccurs="0"/>
 *         &lt;element name="ComputePools" type="{}ComputePoolCostListType" minOccurs="0"/>
 *         &lt;element name="PhysicalServers" type="{}DeviceCostListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceMeteredBillingEnvironmentType", propOrder = {
    "total",
    "computePools",
    "physicalServers"
})
public class DeviceMeteredBillingEnvironmentType
    extends ReferenceType
{

    /**
     *
     */
    private static final long serialVersionUID = -3196766135332862370L;
    @XmlElementRef(name = "Total", type = JAXBElement.class, required = false)
    protected JAXBElement<CostType> total;
    @XmlElementRef(name = "ComputePools", type = JAXBElement.class, required = false)
    protected JAXBElement<ComputePoolCostListType> computePools;
    @XmlElementRef(name = "PhysicalServers", type = JAXBElement.class, required = false)
    protected JAXBElement<DeviceCostListType> physicalServers;

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CostType }{@code >}
     *     
     */
    public JAXBElement<CostType> getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CostType }{@code >}
     *     
     */
    public void setTotal(JAXBElement<CostType> value) {
        this.total = value;
    }

    /**
     * Gets the value of the computePools property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ComputePoolCostListType }{@code >}
     *     
     */
    public JAXBElement<ComputePoolCostListType> getComputePools() {
        return computePools;
    }

    /**
     * Sets the value of the computePools property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ComputePoolCostListType }{@code >}
     *     
     */
    public void setComputePools(JAXBElement<ComputePoolCostListType> value) {
        this.computePools = value;
    }

    /**
     * Gets the value of the physicalServers property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DeviceCostListType }{@code >}
     *     
     */
    public JAXBElement<DeviceCostListType> getPhysicalServers() {
        return physicalServers;
    }

    /**
     * Sets the value of the physicalServers property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DeviceCostListType }{@code >}
     *     
     */
    public void setPhysicalServers(JAXBElement<DeviceCostListType> value) {
        this.physicalServers = value;
    }

}
