//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceNetworkType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DeviceNetworkType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="IpAddresses" type="{}DeviceIpsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceNetworkType", propOrder = {
    "ipAddresses"
})
public class DeviceNetworkType
    extends ResourceType {

    @XmlElementRef(name = "IpAddresses", type = JAXBElement.class, required = false)
    protected JAXBElement<DeviceIpsType> ipAddresses;

    /**
     * Gets the value of the ipAddresses property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link DeviceIpsType }{@code >}
     */
    public JAXBElement<DeviceIpsType> getIpAddresses() {
        return ipAddresses;
    }

    /**
     * Sets the value of the ipAddresses property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link DeviceIpsType }{@code >}
     */
    public void setIpAddresses(JAXBElement<DeviceIpsType> value) {
        this.ipAddresses = value;
    }

}
