//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DisasterRecoveryStatusType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DisasterRecoveryStatusType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="DisasterRecoveryState" type="{}DisasterRecoveryStateTypeEnum" minOccurs="0"/>
 *         &lt;element name="InitiatedBy" type="{}InitiatedByType" minOccurs="0"/>
 *         &lt;element name="DisasterRecoveryOperations" type="{}ArrayOfDisasterRecoveryOperationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisasterRecoveryStatusType", propOrder = {
    "disasterRecoveryState",
    "initiatedBy",
    "disasterRecoveryOperations"
})
public class DisasterRecoveryStatusType
    extends EntityType {

    @XmlElement(name = "DisasterRecoveryState")
    @XmlSchemaType(name = "string")
    protected DisasterRecoveryStateTypeEnum disasterRecoveryState;
    @XmlElementRef(name = "InitiatedBy", type = JAXBElement.class, required = false)
    protected JAXBElement<InitiatedByType> initiatedBy;
    @XmlElementRef(name = "DisasterRecoveryOperations", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfDisasterRecoveryOperationType> disasterRecoveryOperations;

    /**
     * Gets the value of the disasterRecoveryState property.
     *
     * @return possible object is
     * {@link DisasterRecoveryStateTypeEnum }
     */
    public DisasterRecoveryStateTypeEnum getDisasterRecoveryState() {
        return disasterRecoveryState;
    }

    /**
     * Sets the value of the disasterRecoveryState property.
     *
     * @param value allowed object is
     *              {@link DisasterRecoveryStateTypeEnum }
     */
    public void setDisasterRecoveryState(DisasterRecoveryStateTypeEnum value) {
        this.disasterRecoveryState = value;
    }

    /**
     * Gets the value of the initiatedBy property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link InitiatedByType }{@code >}
     */
    public JAXBElement<InitiatedByType> getInitiatedBy() {
        return initiatedBy;
    }

    /**
     * Sets the value of the initiatedBy property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link InitiatedByType }{@code >}
     */
    public void setInitiatedBy(JAXBElement<InitiatedByType> value) {
        this.initiatedBy = value;
    }

    /**
     * Gets the value of the disasterRecoveryOperations property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ArrayOfDisasterRecoveryOperationType }{@code >}
     */
    public JAXBElement<ArrayOfDisasterRecoveryOperationType> getDisasterRecoveryOperations() {
        return disasterRecoveryOperations;
    }

    /**
     * Sets the value of the disasterRecoveryOperations property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ArrayOfDisasterRecoveryOperationType }{@code >}
     */
    public void setDisasterRecoveryOperations(JAXBElement<ArrayOfDisasterRecoveryOperationType> value) {
        this.disasterRecoveryOperations = value;
    }

}
