//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for DisasterRecoveryType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="DisasterRecoveryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DisasterRecoveryState" type="{}DisasterRecoveryStateTypeEnum" minOccurs="0"/>
 *         &lt;element name="PrimaryEnvironment" type="{}ReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisasterRecoveryType", propOrder = {
    "disasterRecoveryState",
    "primaryEnvironment"
})
public class DisasterRecoveryType {

    @XmlElement(name = "DisasterRecoveryState")
    @XmlSchemaType(name = "string")
    protected DisasterRecoveryStateTypeEnum disasterRecoveryState;
    @XmlElementRef(name = "PrimaryEnvironment", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> primaryEnvironment;

    /**
     * Gets the value of the disasterRecoveryState property.
     *
     * @return possible object is
     * {@link DisasterRecoveryStateTypeEnum }
     */
    public DisasterRecoveryStateTypeEnum getDisasterRecoveryState() {
        return disasterRecoveryState;
    }

    /**
     * Sets the value of the disasterRecoveryState property.
     *
     * @param value allowed object is
     *              {@link DisasterRecoveryStateTypeEnum }
     */
    public void setDisasterRecoveryState(DisasterRecoveryStateTypeEnum value) {
        this.disasterRecoveryState = value;
    }

    /**
     * Gets the value of the primaryEnvironment property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getPrimaryEnvironment() {
        return primaryEnvironment;
    }

    /**
     * Sets the value of the primaryEnvironment property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setPrimaryEnvironment(JAXBElement<ReferenceType> value) {
        this.primaryEnvironment = value;
    }

}
