//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnvironmentType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="EnvironmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="ComputePools" type="{}ComputePoolReferencesType" minOccurs="0"/>
 *         &lt;element name="Networks" type="{}NetworkReferencesType" minOccurs="0"/>
 *         &lt;element name="PhysicalDevices" type="{}PhysicalDeviceReferencesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnvironmentType", propOrder = {
    "computePools",
    "networks",
    "physicalDevices"
})
public class EnvironmentType
    extends EntityType {

    @XmlElementRef(name = "ComputePools", type = JAXBElement.class, required = false)
    protected JAXBElement<ComputePoolReferencesType> computePools;
    @XmlElementRef(name = "Networks", type = JAXBElement.class, required = false)
    protected JAXBElement<NetworkReferencesType> networks;
    @XmlElementRef(name = "PhysicalDevices", type = JAXBElement.class, required = false)
    protected JAXBElement<PhysicalDeviceReferencesType> physicalDevices;

    /**
     * Gets the value of the computePools property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ComputePoolReferencesType }{@code >}
     */
    public JAXBElement<ComputePoolReferencesType> getComputePools() {
        return computePools;
    }

    /**
     * Sets the value of the computePools property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ComputePoolReferencesType }{@code >}
     */
    public void setComputePools(JAXBElement<ComputePoolReferencesType> value) {
        this.computePools = value;
    }

    /**
     * Gets the value of the networks property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link NetworkReferencesType }{@code >}
     */
    public JAXBElement<NetworkReferencesType> getNetworks() {
        return networks;
    }

    /**
     * Sets the value of the networks property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link NetworkReferencesType }{@code >}
     */
    public void setNetworks(JAXBElement<NetworkReferencesType> value) {
        this.networks = value;
    }

    /**
     * Gets the value of the physicalDevices property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link PhysicalDeviceReferencesType }{@code >}
     */
    public JAXBElement<PhysicalDeviceReferencesType> getPhysicalDevices() {
        return physicalDevices;
    }

    /**
     * Sets the value of the physicalDevices property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link PhysicalDeviceReferencesType }{@code >}
     */
    public void setPhysicalDevices(JAXBElement<PhysicalDeviceReferencesType> value) {
        this.physicalDevices = value;
    }

}
