//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for FirewallAclEndpointType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="FirewallAclEndpointType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{}FirewallAclEndpointTypeEnum" minOccurs="0"/>
 *         &lt;element name="ExternalIpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalNetwork" type="{}ExternalNetworkType" minOccurs="0"/>
 *         &lt;element name="IpAddress" type="{}IpAddressReferenceType" minOccurs="0"/>
 *         &lt;element name="Network" type="{}NetworkReferenceType" minOccurs="0"/>
 *         &lt;element name="TrustedNetworkGroup" type="{}ReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FirewallAclEndpointType", propOrder = {
    "type",
    "externalIpAddress",
    "externalNetwork",
    "ipAddress",
    "network",
    "trustedNetworkGroup"
})
public class FirewallAclEndpointType {

    @XmlElement(name = "Type")
    @XmlSchemaType(name = "string")
    protected FirewallAclEndpointTypeEnum type;
    @XmlElementRef(name = "ExternalIpAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<String> externalIpAddress;
    @XmlElementRef(name = "ExternalNetwork", type = JAXBElement.class, required = false)
    protected JAXBElement<ExternalNetworkType> externalNetwork;
    @XmlElementRef(name = "IpAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<IpAddressReferenceType> ipAddress;
    @XmlElementRef(name = "Network", type = JAXBElement.class, required = false)
    protected JAXBElement<NetworkReferenceType> network;
    @XmlElementRef(name = "TrustedNetworkGroup", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> trustedNetworkGroup;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link FirewallAclEndpointTypeEnum }
     */
    public FirewallAclEndpointTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link FirewallAclEndpointTypeEnum }
     */
    public void setType(FirewallAclEndpointTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the externalIpAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getExternalIpAddress() {
        return externalIpAddress;
    }

    /**
     * Sets the value of the externalIpAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setExternalIpAddress(JAXBElement<String> value) {
        this.externalIpAddress = value;
    }

    /**
     * Gets the value of the externalNetwork property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ExternalNetworkType }{@code >}
     */
    public JAXBElement<ExternalNetworkType> getExternalNetwork() {
        return externalNetwork;
    }

    /**
     * Sets the value of the externalNetwork property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ExternalNetworkType }{@code >}
     */
    public void setExternalNetwork(JAXBElement<ExternalNetworkType> value) {
        this.externalNetwork = value;
    }

    /**
     * Gets the value of the ipAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link IpAddressReferenceType }{@code >}
     */
    public JAXBElement<IpAddressReferenceType> getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link IpAddressReferenceType }{@code >}
     */
    public void setIpAddress(JAXBElement<IpAddressReferenceType> value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the network property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link NetworkReferenceType }{@code >}
     */
    public JAXBElement<NetworkReferenceType> getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link NetworkReferenceType }{@code >}
     */
    public void setNetwork(JAXBElement<NetworkReferenceType> value) {
        this.network = value;
    }

    /**
     * Gets the value of the trustedNetworkGroup property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getTrustedNetworkGroup() {
        return trustedNetworkGroup;
    }

    /**
     * Sets the value of the trustedNetworkGroup property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setTrustedNetworkGroup(JAXBElement<ReferenceType> value) {
        this.trustedNetworkGroup = value;
    }

}
