//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for HistoricalUsageType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="HistoricalUsageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Month" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Year" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Billable" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Burst" type="{}ResourceUnitType" minOccurs="0"/>
 *         &lt;element name="Total" type="{}ResourceUnitType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoricalUsageType", propOrder = {
    "month",
    "year",
    "billable",
    "burst",
    "total"
})
public class HistoricalUsageType {

    @XmlElement(name = "Month")
    protected Integer month;
    @XmlElement(name = "Year")
    protected Integer year;
    @XmlElementRef(name = "Billable", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> billable;
    @XmlElementRef(name = "Burst", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> burst;
    @XmlElementRef(name = "Total", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> total;

    /**
     * Gets the value of the month property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setMonth(Integer value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setYear(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the billable property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getBillable() {
        return billable;
    }

    /**
     * Sets the value of the billable property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setBillable(JAXBElement<ResourceUnitType> value) {
        this.billable = value;
    }

    /**
     * Gets the value of the burst property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getBurst() {
        return burst;
    }

    /**
     * Sets the value of the burst property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setBurst(JAXBElement<ResourceUnitType> value) {
        this.burst = value;
    }

    /**
     * Gets the value of the total property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setTotal(JAXBElement<ResourceUnitType> value) {
        this.total = value;
    }

}
