//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.io.Serializable;


/**
 * <p>Java class for ImportVirtualMachineType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ImportVirtualMachineType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CreateVirtualMachineRequestType">
 *       &lt;sequence>
 *         &lt;element name="CatalogEntry" type="{}ReferenceType"/>
 *         &lt;element name="NetworkMappings" type="{}ImportNetworkMappingsType"/>
 *         &lt;element name="OperatingSystem" type="{}ReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImportVirtualMachineType", propOrder = {
    "catalogEntry",
    "networkMappings",
    "operatingSystem"
})
public class ImportVirtualMachineType
    extends CreateVirtualMachineRequestType implements Serializable {

    private static final long serialVersionUID = 8906105412253323245L;

    @XmlElement(name = "CatalogEntry", required = true, nillable = true)
    protected ReferenceType catalogEntry;
    @XmlElement(name = "NetworkMappings", required = true, nillable = true)
    protected ImportNetworkMappingsType networkMappings;
    @XmlElementRef(name = "OperatingSystem", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> operatingSystem;

    /**
     * Gets the value of the catalogEntry property.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getCatalogEntry() {
        return catalogEntry;
    }

    /**
     * Sets the value of the catalogEntry property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setCatalogEntry(ReferenceType value) {
        this.catalogEntry = value;
    }

    /**
     * Gets the value of the networkMappings property.
     *
     * @return possible object is
     * {@link ImportNetworkMappingsType }
     */
    public ImportNetworkMappingsType getNetworkMappings() {
        return networkMappings;
    }

    /**
     * Sets the value of the networkMappings property.
     *
     * @param value allowed object is
     *              {@link ImportNetworkMappingsType }
     */
    public void setNetworkMappings(ImportNetworkMappingsType value) {
        this.networkMappings = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setOperatingSystem(JAXBElement<ReferenceType> value) {
        this.operatingSystem = value;
    }

}
