//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for InternetServicePersistenceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="InternetServicePersistenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{}PersistenceTypeEnum" minOccurs="0"/>
 *         &lt;element name="Timeout" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternetServicePersistenceType", propOrder = {
    "type",
    "timeout"
})
public class InternetServicePersistenceType {

    @XmlElement(name = "Type")
    @XmlSchemaType(name = "string")
    protected PersistenceTypeEnum type;
    @XmlElementRef(name = "Timeout", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> timeout;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link PersistenceTypeEnum }
     */
    public PersistenceTypeEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link PersistenceTypeEnum }
     */
    public void setType(PersistenceTypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the timeout property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    public JAXBElement<Long> getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    public void setTimeout(JAXBElement<Long> value) {
        this.timeout = value;
    }

}
