//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for LayoutRowType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="LayoutRowType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="Index" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Groups" type="{}GroupsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutRowType", propOrder = {
    "index",
    "groups"
})
public class LayoutRowType
    extends ResourceType {

    @XmlElement(name = "Index")
    protected Integer index;
    @XmlElementRef(name = "Groups", type = JAXBElement.class, required = false)
    protected JAXBElement<GroupsType> groups;

    /**
     * Gets the value of the index property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setIndex(Integer value) {
        this.index = value;
    }

    /**
     * Gets the value of the groups property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link GroupsType }{@code >}
     */
    public JAXBElement<GroupsType> getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link GroupsType }{@code >}
     */
    public void setGroups(JAXBElement<GroupsType> value) {
        this.groups = value;
    }

}
