//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LicenseUsageType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="LicenseUsageType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceUsageType">
 *       &lt;sequence>
 *         &lt;element name="Usage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicenseUsageType", propOrder = {
    "usage"
})
public class LicenseUsageType
    extends ResourceUsageType {

    @XmlElement(name = "Usage")
    protected Integer usage;

    /**
     * Gets the value of the usage property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setUsage(Integer value) {
        this.usage = value;
    }

}
