//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for MemoryUsageDetailsType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MemoryUsageDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MemoryUsageDetail" type="{}ComputePoolMemoryUsageDetailSummaryEntryType"
 *         maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemoryUsageDetailsType", propOrder = {
    "memoryUsageDetail"
})
public class MemoryUsageDetailsType {

    @XmlElement(name = "MemoryUsageDetail", nillable = true)
    protected List<ComputePoolMemoryUsageDetailSummaryEntryType> memoryUsageDetail;

    /**
     * Gets the value of the memoryUsageDetail property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memoryUsageDetail property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemoryUsageDetail().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ComputePoolMemoryUsageDetailSummaryEntryType }
     */
    public List<ComputePoolMemoryUsageDetailSummaryEntryType> getMemoryUsageDetail() {
        if (memoryUsageDetail == null) {
            memoryUsageDetail = new ArrayList<ComputePoolMemoryUsageDetailSummaryEntryType>();
        }
        return this.memoryUsageDetail;
    }

}
