//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MeteredBillingEnvironmentType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MeteredBillingEnvironmentType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ReferenceType">
 *       &lt;sequence>
 *         &lt;element name="Total" type="{}CostType" minOccurs="0"/>
 *         &lt;element name="ReservedBilling" type="{}ReservedBillingType" minOccurs="0"/>
 *         &lt;element name="InstanceBasedBilling" type="{}InstanceBasedBillingType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteredBillingEnvironmentType", propOrder = {
    "total",
    "reservedBilling",
    "instanceBasedBilling"
})
public class MeteredBillingEnvironmentType
    extends ReferenceType {

    /**
     *
     */
    private static final long serialVersionUID = 487845470107146056L;
    @XmlElementRef(name = "Total", type = JAXBElement.class, required = false)
    protected JAXBElement<CostType> total;
    @XmlElementRef(name = "ReservedBilling", type = JAXBElement.class, required = false)
    protected JAXBElement<ReservedBillingType> reservedBilling;
    @XmlElementRef(name = "InstanceBasedBilling", type = JAXBElement.class, required = false)
    protected JAXBElement<InstanceBasedBillingType> instanceBasedBilling;

    /**
     * Gets the value of the total property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link CostType }{@code >}
     */
    public JAXBElement<CostType> getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link CostType }{@code >}
     */
    public void setTotal(JAXBElement<CostType> value) {
        this.total = value;
    }

    /**
     * Gets the value of the reservedBilling property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReservedBillingType }{@code >}
     */
    public JAXBElement<ReservedBillingType> getReservedBilling() {
        return reservedBilling;
    }

    /**
     * Sets the value of the reservedBilling property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReservedBillingType }{@code >}
     */
    public void setReservedBilling(JAXBElement<ReservedBillingType> value) {
        this.reservedBilling = value;
    }

    /**
     * Gets the value of the instanceBasedBilling property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link InstanceBasedBillingType }{@code >}
     */
    public JAXBElement<InstanceBasedBillingType> getInstanceBasedBilling() {
        return instanceBasedBilling;
    }

    /**
     * Sets the value of the instanceBasedBilling property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link InstanceBasedBillingType }{@code >}
     */
    public void setInstanceBasedBilling(JAXBElement<InstanceBasedBillingType> value) {
        this.instanceBasedBilling = value;
    }

}
