//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MirrorErrorDataType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MirrorErrorDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorSummaryMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorDetailedMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MirrorErrorDataType", propOrder = {
    "errorSummaryMessage",
    "errorDetailedMessage"
})
public class MirrorErrorDataType {

    @XmlElementRef(name = "ErrorSummaryMessage", type = JAXBElement.class, required = false)
    protected JAXBElement<String> errorSummaryMessage;
    @XmlElementRef(name = "ErrorDetailedMessage", type = JAXBElement.class, required = false)
    protected JAXBElement<String> errorDetailedMessage;

    /**
     * Gets the value of the errorSummaryMessage property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getErrorSummaryMessage() {
        return errorSummaryMessage;
    }

    /**
     * Sets the value of the errorSummaryMessage property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setErrorSummaryMessage(JAXBElement<String> value) {
        this.errorSummaryMessage = value;
    }

    /**
     * Gets the value of the errorDetailedMessage property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getErrorDetailedMessage() {
        return errorDetailedMessage;
    }

    /**
     * Sets the value of the errorDetailedMessage property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setErrorDetailedMessage(JAXBElement<String> value) {
        this.errorDetailedMessage = value;
    }

}
