//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MonitoringCloudServiceDeviceConfigurationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MonitoringCloudServiceDeviceConfigurationType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CloudServiceDeviceConfigurationType">
 *       &lt;sequence>
 *         &lt;element name="Recipients" type="{}RecipientsType"/>
 *         &lt;element name="MonitoringCloudServiceThresholds" type="{}MonitoringCloudServiceThresholdsType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MonitoringCloudServiceDeviceConfigurationType", propOrder = {
    "recipients",
    "monitoringCloudServiceThresholds"
})
public class MonitoringCloudServiceDeviceConfigurationType
    extends CloudServiceDeviceConfigurationType {

    @XmlElement(name = "Recipients", required = true, nillable = true)
    protected RecipientsType recipients;
    @XmlElement(name = "MonitoringCloudServiceThresholds", required = true, nillable = true)
    protected MonitoringCloudServiceThresholdsType monitoringCloudServiceThresholds;

    /**
     * Gets the value of the recipients property.
     *
     * @return possible object is
     * {@link RecipientsType }
     */
    public RecipientsType getRecipients() {
        return recipients;
    }

    /**
     * Sets the value of the recipients property.
     *
     * @param value allowed object is
     *              {@link RecipientsType }
     */
    public void setRecipients(RecipientsType value) {
        this.recipients = value;
    }

    /**
     * Gets the value of the monitoringCloudServiceThresholds property.
     *
     * @return possible object is
     * {@link MonitoringCloudServiceThresholdsType }
     */
    public MonitoringCloudServiceThresholdsType getMonitoringCloudServiceThresholds() {
        return monitoringCloudServiceThresholds;
    }

    /**
     * Sets the value of the monitoringCloudServiceThresholds property.
     *
     * @param value allowed object is
     *              {@link MonitoringCloudServiceThresholdsType }
     */
    public void setMonitoringCloudServiceThresholds(MonitoringCloudServiceThresholdsType value) {
        this.monitoringCloudServiceThresholds = value;
    }

}
