//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for NetworkType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="NetworkType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetworkType" type="{}NetworkTypeEnum" minOccurs="0"/>
 *         &lt;element name="BroadcastAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GatewayAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RnatAddress" type="{}ReferenceType" minOccurs="0"/>
 *         &lt;element name="IpAddresses" type="{}IpAddressesType" minOccurs="0"/>
 *         &lt;element name="NetworkOverlay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkType", propOrder = {
    "address",
    "networkType",
    "broadcastAddress",
    "gatewayAddress",
    "rnatAddress",
    "ipAddresses",
    "networkOverlay",
    "description"
})
public class NetworkType
    extends ResourceType {

    @XmlElementRef(name = "Address", type = JAXBElement.class, required = false)
    protected JAXBElement<String> address;
    @XmlElement(name = "NetworkType")
    @XmlSchemaType(name = "string")
    protected NetworkTypeEnum networkType;
    @XmlElementRef(name = "BroadcastAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<String> broadcastAddress;
    @XmlElementRef(name = "GatewayAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<String> gatewayAddress;
    @XmlElementRef(name = "RnatAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> rnatAddress;
    @XmlElementRef(name = "IpAddresses", type = JAXBElement.class, required = false)
    protected JAXBElement<IpAddressesType> ipAddresses;
    @XmlElement(name = "NetworkOverlay")
    protected Boolean networkOverlay;
    @XmlElementRef(name = "Description", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;

    /**
     * Gets the value of the address property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setAddress(JAXBElement<String> value) {
        this.address = value;
    }

    /**
     * Gets the value of the networkType property.
     *
     * @return possible object is
     * {@link NetworkTypeEnum }
     */
    public NetworkTypeEnum getNetworkType() {
        return networkType;
    }

    /**
     * Sets the value of the networkType property.
     *
     * @param value allowed object is
     *              {@link NetworkTypeEnum }
     */
    public void setNetworkType(NetworkTypeEnum value) {
        this.networkType = value;
    }

    /**
     * Gets the value of the broadcastAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getBroadcastAddress() {
        return broadcastAddress;
    }

    /**
     * Sets the value of the broadcastAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setBroadcastAddress(JAXBElement<String> value) {
        this.broadcastAddress = value;
    }

    /**
     * Gets the value of the gatewayAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getGatewayAddress() {
        return gatewayAddress;
    }

    /**
     * Sets the value of the gatewayAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setGatewayAddress(JAXBElement<String> value) {
        this.gatewayAddress = value;
    }

    /**
     * Gets the value of the rnatAddress property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getRnatAddress() {
        return rnatAddress;
    }

    /**
     * Sets the value of the rnatAddress property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setRnatAddress(JAXBElement<ReferenceType> value) {
        this.rnatAddress = value;
    }

    /**
     * Gets the value of the ipAddresses property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link IpAddressesType }{@code >}
     */
    public JAXBElement<IpAddressesType> getIpAddresses() {
        return ipAddresses;
    }

    /**
     * Sets the value of the ipAddresses property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link IpAddressesType }{@code >}
     */
    public void setIpAddresses(JAXBElement<IpAddressesType> value) {
        this.ipAddresses = value;
    }

    /**
     * Gets the value of the networkOverlay property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isNetworkOverlay() {
        return networkOverlay;
    }

    /**
     * Sets the value of the networkOverlay property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setNetworkOverlay(Boolean value) {
        this.networkOverlay = value;
    }

    /**
     * Gets the value of the description property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

}
