//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for NetworkSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NetworkAdapterSettings" type="{}NetworkAdapterSettingsType"/>
 *         &lt;element name="DnsSettings" type="{}DnsSettingsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkSettingsType", propOrder = {
    "networkAdapterSettings",
    "dnsSettings"
})
public class NetworkSettingsType {

    @XmlElement(name = "NetworkAdapterSettings", required = true, nillable = true)
    protected NetworkAdapterSettingsType networkAdapterSettings;
    @XmlElementRef(name = "DnsSettings", type = JAXBElement.class, required = false)
    protected JAXBElement<DnsSettingsType> dnsSettings;

    /**
     * Gets the value of the networkAdapterSettings property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkAdapterSettingsType }
     *     
     */
    public NetworkAdapterSettingsType getNetworkAdapterSettings() {
        return networkAdapterSettings;
    }

    /**
     * Sets the value of the networkAdapterSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkAdapterSettingsType }
     *     
     */
    public void setNetworkAdapterSettings(NetworkAdapterSettingsType value) {
        this.networkAdapterSettings = value;
    }

    /**
     * Gets the value of the dnsSettings property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DnsSettingsType }{@code >}
     *     
     */
    public JAXBElement<DnsSettingsType> getDnsSettings() {
        return dnsSettings;
    }

    /**
     * Sets the value of the dnsSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DnsSettingsType }{@code >}
     *     
     */
    public void setDnsSettings(JAXBElement<DnsSettingsType> value) {
        this.dnsSettings = value;
    }

}
