//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkRnatType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="NetworkRnatType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="Network" type="{}NetworkReferenceType" minOccurs="0"/>
 *         &lt;element name="Rnat" type="{}ReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkRnatType", propOrder = {
    "network",
    "rnat"
})
public class NetworkRnatType
    extends ResourceType {

    @XmlElementRef(name = "Network", type = JAXBElement.class, required = false)
    protected JAXBElement<NetworkReferenceType> network;
    @XmlElementRef(name = "Rnat", type = JAXBElement.class, required = false)
    protected JAXBElement<ReferenceType> rnat;

    /**
     * Gets the value of the network property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link NetworkReferenceType }{@code >}
     */
    public JAXBElement<NetworkReferenceType> getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link NetworkReferenceType }{@code >}
     */
    public void setNetwork(JAXBElement<NetworkReferenceType> value) {
        this.network = value;
    }

    /**
     * Gets the value of the rnat property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public JAXBElement<ReferenceType> getRnat() {
        return rnat;
    }

    /**
     * Sets the value of the rnat property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    public void setRnat(JAXBElement<ReferenceType> value) {
        this.rnat = value;
    }

}
