//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NetworkHostSummaryNetworkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkHostSummaryNetworkType">
 *   &lt;complexContent>
 *     &lt;extension base="{}NetworkReferenceType">
 *       &lt;sequence>
 *         &lt;element name="Hosts" type="{}NetworkHostSummaryHostsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkHostSummaryNetworkType", propOrder = {
    "hosts"
})
public class NetworkHostSummaryNetworkType
    extends NetworkReferenceType
{

    /**
     *
     */
    private static final long serialVersionUID = -6948129387651577357L;
    @XmlElementRef(name = "Hosts", type = JAXBElement.class, required = false)
    protected JAXBElement<NetworkHostSummaryHostsType> hosts;

    /**
     * Gets the value of the hosts property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NetworkHostSummaryHostsType }{@code >}
     *     
     */
    public JAXBElement<NetworkHostSummaryHostsType> getHosts() {
        return hosts;
    }

    /**
     * Sets the value of the hosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NetworkHostSummaryHostsType }{@code >}
     *     
     */
    public void setHosts(JAXBElement<NetworkHostSummaryHostsType> value) {
        this.hosts = value;
    }

}
