//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for NodeServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeServiceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="IpAddress" type="{}IpAddressReferenceType" minOccurs="0"/>
 *         &lt;element name="Protocol" type="{}ProtocolTypeEnum" minOccurs="0"/>
 *         &lt;element name="Port" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="PortRanges" type="{}PortRangesType" minOccurs="0"/>
 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeServiceType", propOrder = {
    "ipAddress",
    "protocol",
    "port",
    "portRanges",
    "enabled",
    "description"
})
public class NodeServiceType
    extends EntityType
{

    @XmlElementRef(name = "IpAddress", type = JAXBElement.class, required = false)
    protected JAXBElement<IpAddressReferenceType> ipAddress;
    @XmlElement(name = "Protocol")
    @XmlSchemaType(name = "string")
    protected ProtocolTypeEnum protocol;
    @XmlElementRef(name = "Port", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> port;
    @XmlElementRef(name = "PortRanges", type = JAXBElement.class, required = false)
    protected JAXBElement<PortRangesType> portRanges;
    @XmlElement(name = "Enabled")
    protected boolean enabled;
    @XmlElementRef(name = "Description", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;

    /**
     * Gets the value of the ipAddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link IpAddressReferenceType }{@code >}
     *     
     */
    public JAXBElement<IpAddressReferenceType> getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the value of the ipAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link IpAddressReferenceType }{@code >}
     *     
     */
    public void setIpAddress(JAXBElement<IpAddressReferenceType> value) {
        this.ipAddress = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolTypeEnum }
     *     
     */
    public ProtocolTypeEnum getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolTypeEnum }
     *     
     */
    public void setProtocol(ProtocolTypeEnum value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setPort(JAXBElement<Long> value) {
        this.port = value;
    }

    /**
     * Gets the value of the portRanges property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PortRangesType }{@code >}
     *     
     */
    public JAXBElement<PortRangesType> getPortRanges() {
        return portRanges;
    }

    /**
     * Sets the value of the portRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PortRangesType }{@code >}
     *     
     */
    public void setPortRanges(JAXBElement<PortRangesType> value) {
        this.portRanges = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

}
