//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PasswordExpirationType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="PasswordExpirationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PasswordExpirationEnforced" type="{http://www.w3.org/2001/XMLSchema}boolean"
 *         minOccurs="0"/>
 *         &lt;element name="ExpirationInDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ExpirationNoticeInDays" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DoNotExpireBeforeDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PasswordExpirationType", propOrder = {
    "passwordExpirationEnforced",
    "expirationInDays",
    "expirationNoticeInDays",
    "doNotExpireBeforeDate"
})
public class PasswordExpirationType {

    @XmlElementRef(name = "PasswordExpirationEnforced", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> passwordExpirationEnforced;
    @XmlElementRef(name = "ExpirationInDays", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> expirationInDays;
    @XmlElementRef(name = "ExpirationNoticeInDays", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> expirationNoticeInDays;
    @XmlElementRef(name = "DoNotExpireBeforeDate", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> doNotExpireBeforeDate;

    /**
     * Gets the value of the passwordExpirationEnforced property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    public JAXBElement<Boolean> getPasswordExpirationEnforced() {
        return passwordExpirationEnforced;
    }

    /**
     * Sets the value of the passwordExpirationEnforced property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     */
    public void setPasswordExpirationEnforced(JAXBElement<Boolean> value) {
        this.passwordExpirationEnforced = value;
    }

    /**
     * Gets the value of the expirationInDays property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public JAXBElement<Integer> getExpirationInDays() {
        return expirationInDays;
    }

    /**
     * Sets the value of the expirationInDays property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public void setExpirationInDays(JAXBElement<Integer> value) {
        this.expirationInDays = value;
    }

    /**
     * Gets the value of the expirationNoticeInDays property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public JAXBElement<Integer> getExpirationNoticeInDays() {
        return expirationNoticeInDays;
    }

    /**
     * Sets the value of the expirationNoticeInDays property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    public void setExpirationNoticeInDays(JAXBElement<Integer> value) {
        this.expirationNoticeInDays = value;
    }

    /**
     * Gets the value of the doNotExpireBeforeDate property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public JAXBElement<XMLGregorianCalendar> getDoNotExpireBeforeDate() {
        return doNotExpireBeforeDate;
    }

    /**
     * Sets the value of the doNotExpireBeforeDate property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    public void setDoNotExpireBeforeDate(JAXBElement<XMLGregorianCalendar> value) {
        this.doNotExpireBeforeDate = value;
    }

}
