//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalServerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicalServerType">
 *   &lt;complexContent>
 *     &lt;extension base="{}PhysicalDeviceType">
 *       &lt;sequence>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LightsOutIp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OperatingSystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AssignedIpAddresses" type="{}AssignedIpAddressesType" minOccurs="0"/>
 *         &lt;element name="LicensedSoftware" type="{}PhysicalDeviceLicensedSoftwareType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalServerType", propOrder = {
    "serialNumber",
    "lightsOutIp",
    "operatingSystem",
    "assignedIpAddresses",
    "licensedSoftware"
})
public class PhysicalServerType
    extends PhysicalDeviceType
{

    @XmlElementRef(name = "SerialNumber", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serialNumber;
    @XmlElementRef(name = "LightsOutIp", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lightsOutIp;
    @XmlElementRef(name = "OperatingSystem", type = JAXBElement.class, required = false)
    protected JAXBElement<String> operatingSystem;
    @XmlElementRef(name = "AssignedIpAddresses", type = JAXBElement.class, required = false)
    protected JAXBElement<AssignedIpAddressesType> assignedIpAddresses;
    @XmlElementRef(name = "LicensedSoftware", type = JAXBElement.class, required = false)
    protected JAXBElement<PhysicalDeviceLicensedSoftwareType> licensedSoftware;

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSerialNumber(JAXBElement<String> value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the lightsOutIp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLightsOutIp() {
        return lightsOutIp;
    }

    /**
     * Sets the value of the lightsOutIp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLightsOutIp(JAXBElement<String> value) {
        this.lightsOutIp = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOperatingSystem(JAXBElement<String> value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the assignedIpAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AssignedIpAddressesType }{@code >}
     *     
     */
    public JAXBElement<AssignedIpAddressesType> getAssignedIpAddresses() {
        return assignedIpAddresses;
    }

    /**
     * Sets the value of the assignedIpAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AssignedIpAddressesType }{@code >}
     *     
     */
    public void setAssignedIpAddresses(JAXBElement<AssignedIpAddressesType> value) {
        this.assignedIpAddresses = value;
    }

    /**
     * Gets the value of the licensedSoftware property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PhysicalDeviceLicensedSoftwareType }{@code >}
     *     
     */
    public JAXBElement<PhysicalDeviceLicensedSoftwareType> getLicensedSoftware() {
        return licensedSoftware;
    }

    /**
     * Sets the value of the licensedSoftware property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PhysicalDeviceLicensedSoftwareType }{@code >}
     *     
     */
    public void setLicensedSoftware(JAXBElement<PhysicalDeviceLicensedSoftwareType> value) {
        this.licensedSoftware = value;
    }

}
