//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicalDeviceLicensedSoftwareType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="PhysicalDeviceLicensedSoftwareType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HourlyLicensedSoftware" type="{}ArrayOfPhysicalServerSoftwareEntryType" minOccurs="0"/>
 *         &lt;element name="LicenseProvider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MonthlyLicensedSoftware" type="{}ArrayOfPhysicalServerSoftwareEntryType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalDeviceLicensedSoftwareType", propOrder = {
    "hourlyLicensedSoftware",
    "licenseProvider",
    "monthlyLicensedSoftware"
})
public class PhysicalDeviceLicensedSoftwareType {

    @XmlElementRef(name = "HourlyLicensedSoftware", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> hourlyLicensedSoftware;
    @XmlElementRef(name = "LicenseProvider", type = JAXBElement.class, required = false)
    protected JAXBElement<String> licenseProvider;
    @XmlElementRef(name = "MonthlyLicensedSoftware", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> monthlyLicensedSoftware;

    /**
     * Gets the value of the hourlyLicensedSoftware property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ArrayOfPhysicalServerSoftwareEntryType }{@code >}
     */
    public JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> getHourlyLicensedSoftware() {
        return hourlyLicensedSoftware;
    }

    /**
     * Sets the value of the hourlyLicensedSoftware property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ArrayOfPhysicalServerSoftwareEntryType }{@code >}
     */
    public void setHourlyLicensedSoftware(JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> value) {
        this.hourlyLicensedSoftware = value;
    }

    /**
     * Gets the value of the licenseProvider property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getLicenseProvider() {
        return licenseProvider;
    }

    /**
     * Sets the value of the licenseProvider property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setLicenseProvider(JAXBElement<String> value) {
        this.licenseProvider = value;
    }

    /**
     * Gets the value of the monthlyLicensedSoftware property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ArrayOfPhysicalServerSoftwareEntryType }{@code >}
     */
    public JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> getMonthlyLicensedSoftware() {
        return monthlyLicensedSoftware;
    }

    /**
     * Sets the value of the monthlyLicensedSoftware property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ArrayOfPhysicalServerSoftwareEntryType }{@code >}
     */
    public void setMonthlyLicensedSoftware(JAXBElement<ArrayOfPhysicalServerSoftwareEntryType> value) {
        this.monthlyLicensedSoftware = value;
    }

}
