//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for PublicIpType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="PublicIpType">
 *   &lt;complexContent>
 *     &lt;extension base="{}EntityType">
 *       &lt;sequence>
 *         &lt;element name="PublicIpType" type="{}PublicIpTypeEnum" minOccurs="0"/>
 *         &lt;element name="IsInternal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="InternetServices" type="{}ArrayOfInternetServiceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicIpType", propOrder = {
    "publicIpType",
    "isInternal",
    "internetServices"
})
public class PublicIpType
    extends EntityType {

    @XmlElement(name = "PublicIpType")
    @XmlSchemaType(name = "string")
    protected PublicIpTypeEnum publicIpType;
    @XmlElement(name = "IsInternal")
    protected Boolean isInternal;
    @XmlElementRef(name = "InternetServices", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfInternetServiceType> internetServices;

    /**
     * Gets the value of the publicIpType property.
     *
     * @return possible object is
     * {@link PublicIpTypeEnum }
     */
    public PublicIpTypeEnum getPublicIpType() {
        return publicIpType;
    }

    /**
     * Sets the value of the publicIpType property.
     *
     * @param value allowed object is
     *              {@link PublicIpTypeEnum }
     */
    public void setPublicIpType(PublicIpTypeEnum value) {
        this.publicIpType = value;
    }

    /**
     * Gets the value of the isInternal property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isIsInternal() {
        return isInternal;
    }

    /**
     * Sets the value of the isInternal property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setIsInternal(Boolean value) {
        this.isInternal = value;
    }

    /**
     * Gets the value of the internetServices property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ArrayOfInternetServiceType }{@code >}
     */
    public JAXBElement<ArrayOfInternetServiceType> getInternetServices() {
        return internetServices;
    }

    /**
     * Sets the value of the internetServices property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ArrayOfInternetServiceType }{@code >}
     */
    public void setInternetServices(JAXBElement<ArrayOfInternetServiceType> value) {
        this.internetServices = value;
    }

}
