//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SnapshotType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="SnapshotType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="State" type="{}SnapshotState" minOccurs="0"/>
 *         &lt;element name="SnapshotType" type="{}SnapshotTypeEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SnapshotType", propOrder = {
    "state",
    "snapshotType"
})
public class SnapshotType
    extends ResourceType {

    @XmlElement(name = "State")
    @XmlSchemaType(name = "string")
    protected SnapshotState state;
    @XmlElement(name = "SnapshotType")
    @XmlSchemaType(name = "string")
    protected SnapshotTypeEnum snapshotType;

    /**
     * Gets the value of the state property.
     *
     * @return possible object is
     * {@link SnapshotState }
     */
    public SnapshotState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     *
     * @param value allowed object is
     *              {@link SnapshotState }
     */
    public void setState(SnapshotState value) {
        this.state = value;
    }

    /**
     * Gets the value of the snapshotType property.
     *
     * @return possible object is
     * {@link SnapshotTypeEnum }
     */
    public SnapshotTypeEnum getSnapshotType() {
        return snapshotType;
    }

    /**
     * Sets the value of the snapshotType property.
     *
     * @param value allowed object is
     *              {@link SnapshotTypeEnum }
     */
    public void setSnapshotType(SnapshotTypeEnum value) {
        this.snapshotType = value;
    }

}
