//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StorageDeviceType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="StorageDeviceType">
 *   &lt;complexContent>
 *     &lt;extension base="{}PhysicalDeviceType">
 *       &lt;sequence>
 *         &lt;element name="SerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AssignedIpAddresses" type="{}AssignedIpAddressesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StorageDeviceType", propOrder = {
    "serialNumber",
    "assignedIpAddresses"
})
public class StorageDeviceType
    extends PhysicalDeviceType {

    @XmlElementRef(name = "SerialNumber", type = JAXBElement.class, required = false)
    protected JAXBElement<String> serialNumber;
    @XmlElementRef(name = "AssignedIpAddresses", type = JAXBElement.class, required = false)
    protected JAXBElement<AssignedIpAddressesType> assignedIpAddresses;

    /**
     * Gets the value of the serialNumber property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public JAXBElement<String> getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    public void setSerialNumber(JAXBElement<String> value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the assignedIpAddresses property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link AssignedIpAddressesType }{@code >}
     */
    public JAXBElement<AssignedIpAddressesType> getAssignedIpAddresses() {
        return assignedIpAddresses;
    }

    /**
     * Sets the value of the assignedIpAddresses property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link AssignedIpAddressesType }{@code >}
     */
    public void setAssignedIpAddresses(JAXBElement<AssignedIpAddressesType> value) {
        this.assignedIpAddresses = value;
    }

}
