//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911
// .1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for VirtualMachineStorageUsageDetailType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="VirtualMachineStorageUsageDetailType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ReferenceType">
 *       &lt;sequence>
 *         &lt;element name="DiskCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Allocated" type="{}ResourceUnitType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachineStorageUsageDetailType", propOrder = {
    "diskCount",
    "allocated"
})
public class VirtualMachineStorageUsageDetailType
    extends ReferenceType {

    /**
     *
     */
    private static final long serialVersionUID = -8163796252264589892L;
    @XmlElement(name = "DiskCount")
    protected Integer diskCount;
    @XmlElementRef(name = "Allocated", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitType> allocated;

    /**
     * Gets the value of the diskCount property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getDiskCount() {
        return diskCount;
    }

    /**
     * Sets the value of the diskCount property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setDiskCount(Integer value) {
        this.diskCount = value;
    }

    /**
     * Gets the value of the allocated property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public JAXBElement<ResourceUnitType> getAllocated() {
        return allocated;
    }

    /**
     * Sets the value of the allocated property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link ResourceUnitType }{@code >}
     */
    public void setAllocated(JAXBElement<ResourceUnitType> value) {
        this.allocated = value;
    }

}
