//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.16 at 03:24:22 PM EEST 
//


package org.ecloudmanager.tmrk.cloudapi.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VirtualMachineConfigurationOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VirtualMachineConfigurationOptionsType">
 *   &lt;complexContent>
 *     &lt;extension base="{}ResourceType">
 *       &lt;sequence>
 *         &lt;element name="Processor" type="{}ConfigurationOptionRangeType" minOccurs="0"/>
 *         &lt;element name="Memory" type="{}ResourceUnitRangeType" minOccurs="0"/>
 *         &lt;element name="Disk" type="{}DiskConfigurationOptionType" minOccurs="0"/>
 *         &lt;element name="NetworkAdapter" type="{}ConfigurationOptionRangeType" minOccurs="0"/>
 *         &lt;element name="Customization" type="{}CustomizationOptionType" minOccurs="0"/>
 *         &lt;element name="PriceMatrix" type="{}PriceMatrixType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VirtualMachineConfigurationOptionsType", propOrder = {
    "processor",
    "memory",
    "disk",
    "networkAdapter",
    "customization",
    "priceMatrix"
})
public class VirtualMachineConfigurationOptionsType
    extends ResourceType
{

    @XmlElementRef(name = "Processor", type = JAXBElement.class, required = false)
    protected JAXBElement<ConfigurationOptionRangeType> processor;
    @XmlElementRef(name = "Memory", type = JAXBElement.class, required = false)
    protected JAXBElement<ResourceUnitRangeType> memory;
    @XmlElementRef(name = "Disk", type = JAXBElement.class, required = false)
    protected JAXBElement<DiskConfigurationOptionType> disk;
    @XmlElementRef(name = "NetworkAdapter", type = JAXBElement.class, required = false)
    protected JAXBElement<ConfigurationOptionRangeType> networkAdapter;
    @XmlElementRef(name = "Customization", type = JAXBElement.class, required = false)
    protected JAXBElement<CustomizationOptionType> customization;
    @XmlElementRef(name = "PriceMatrix", type = JAXBElement.class, required = false)
    protected JAXBElement<PriceMatrixType> priceMatrix;

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ConfigurationOptionRangeType }{@code >}
     *     
     */
    public JAXBElement<ConfigurationOptionRangeType> getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ConfigurationOptionRangeType }{@code >}
     *     
     */
    public void setProcessor(JAXBElement<ConfigurationOptionRangeType> value) {
        this.processor = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ResourceUnitRangeType }{@code >}
     *     
     */
    public JAXBElement<ResourceUnitRangeType> getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ResourceUnitRangeType }{@code >}
     *     
     */
    public void setMemory(JAXBElement<ResourceUnitRangeType> value) {
        this.memory = value;
    }

    /**
     * Gets the value of the disk property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link DiskConfigurationOptionType }{@code >}
     *     
     */
    public JAXBElement<DiskConfigurationOptionType> getDisk() {
        return disk;
    }

    /**
     * Sets the value of the disk property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link DiskConfigurationOptionType }{@code >}
     *     
     */
    public void setDisk(JAXBElement<DiskConfigurationOptionType> value) {
        this.disk = value;
    }

    /**
     * Gets the value of the networkAdapter property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ConfigurationOptionRangeType }{@code >}
     *     
     */
    public JAXBElement<ConfigurationOptionRangeType> getNetworkAdapter() {
        return networkAdapter;
    }

    /**
     * Sets the value of the networkAdapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ConfigurationOptionRangeType }{@code >}
     *     
     */
    public void setNetworkAdapter(JAXBElement<ConfigurationOptionRangeType> value) {
        this.networkAdapter = value;
    }

    /**
     * Gets the value of the customization property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CustomizationOptionType }{@code >}
     *     
     */
    public JAXBElement<CustomizationOptionType> getCustomization() {
        return customization;
    }

    /**
     * Sets the value of the customization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CustomizationOptionType }{@code >}
     *     
     */
    public void setCustomization(JAXBElement<CustomizationOptionType> value) {
        this.customization = value;
    }

    /**
     * Gets the value of the priceMatrix property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PriceMatrixType }{@code >}
     *     
     */
    public JAXBElement<PriceMatrixType> getPriceMatrix() {
        return priceMatrix;
    }

    /**
     * Sets the value of the priceMatrix property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PriceMatrixType }{@code >}
     *     
     */
    public void setPriceMatrix(JAXBElement<PriceMatrixType> value) {
        this.priceMatrix = value;
    }

}
